# Definindo nosso environment do app
# setup:
#   addons:
#     - plan: heroku-postgresql
#       as: DATABASE

# Especifica o dockerfile que irá gerar a imagem
build:
  docker:
    web: Dockerfile
    # worker: worker/Dockerfile

# Especifica as tarefas da fase de libertação a serem executadas
# release:
#   command:
#     - ./deployment-task.sh
#     image: worker

# Especifica os tipos de processo e comandos a serem utilizados, caso vazio usa o CMD
# run:
#   web: node index.js

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14


        - name: instalando as dependências
          run: npm install

        - name: executando o lint para verificar se a erros
          run: npx eslint .
